import type { Metadata, Viewport } from "next";
import { ChakraUIProviders } from "@/providers/Chakra";
import { SessionProvider } from "next-auth/react";
import TanstackProvider from "@/providers/Tanstack";
import SmoothScrollbarProvider from "@/providers/SmoothScrollbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <SmoothScrollbarProvider>
          <SessionProvider>
            <TanstackProvider>
              <ChakraUIProviders>{children}</ChakraUIProviders>
            </TanstackProvider>
          </SessionProvider>
        </SmoothScrollbarProvider>
      </body>
    </html>
  );
}
