import type { Metadata } from "next";
import { ChakraUIProviders } from "@/providers/Chakra";
import { SessionProvider } from "next-auth/react";
import TanstackProvider from "@/providers/Tanstack";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <SessionProvider>
          <TanstackProvider>
            <ChakraUIProviders>{children}</ChakraUIProviders>
          </TanstackProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
