name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 
      uses: actions/checkout@v4

    - name: Docker Login
      uses: docker/login-action@v3.3.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESSTOKEN }}

    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v3.6.1
      id: buildx
      
    - name: Check repo
      run: ls -la
      
    - name: Build and push Docker movie-laravel-backend image
      uses: docker/build-push-action@v6.7.0
      id: docker_laravel_build
      with:
        context: ./api-movie-project
        file: prod.Dockerfile
        builder: ${{ steps.buildx.outputs.name }}
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/movie-api-laravel:latest
        
    - name: Build and push Docker nginx-movie-laravel-backend image
      uses: docker/build-push-action@v6.7.0
      id: docker_nginx_laravel_build
      with:
        context: ./api-movie-project
        file: nginx.Dockerfile
        builder: ${{ steps.buildx.outputs.name }}
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/movie-nginx-laravel:latest
        
    - name: Verify
      run: |
        echo ${{ steps.docker_laravel_build.outputs.digest }} \
        && echo ${{ steps.docker_nginx_laravel_build.outputs.digest }}
